// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWFXUz-i80nZcPCY-yBw5CvO5sgUajN5c',
    appId: '1:922216385687:android:20b27f4044a6895520edd2',
    messagingSenderId: '922216385687',
    projectId: 'flutterauth-d3598',
    databaseURL: 'https://flutterauth-d3598-default-rtdb.firebaseio.com',
    storageBucket: 'flutterauth-d3598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbXBCFwBoGMCRJwFqjZ0VhYB6k2z5F-ug',
    appId: '1:922216385687:ios:a56b8b7013dd1d9820edd2',
    messagingSenderId: '922216385687',
    projectId: 'flutterauth-d3598',
    databaseURL: 'https://flutterauth-d3598-default-rtdb.firebaseio.com',
    storageBucket: 'flutterauth-d3598.appspot.com',
    androidClientId: '922216385687-d90t3rhffdtdefq086960cqgdsnrgj5f.apps.googleusercontent.com',
    iosClientId: '922216385687-953bgh7nb7ehuqsgla2r77mdru04rnuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance2',
  );
}
